---
ansible_user: ansible
ansible_become: true
connection_protocol: ssh

# ansible_password: "qwerty"
# ansible_private_key_file: "/home/ansible/.ssh/id_ansible_ed25519" 
# ansible_ssh_private_key_file: "/home/ansible/.ssh/id_ansible_ed25519" 

# ansible_connection: network_cli
# ansible_network_os: ios
# ansible_user: cisco
# ansible_password: cisco
# ansible_become: yes
# ansible_become_method: enable
# ansible_become_pass: cisco
...

