---
# vars file for common

packages_to_install:
  - dnsutils
  - net-tools
  - zabbix-agent
  - rsync
  - rsyslog
  - mc
  - curl
  - wget
  - apt-transport-https
  - gnupg2
  - software-properties-common
  - ca-certificates
  - parted
  - openssh-server
  - nginx
#  - ufw 
  
zbx_server_addr: '192.168.10.11'

allow_ports:
  - "22"
  - "80"
  - "443"
  - "5432"
  - "10050"
...
