---
# tasks file for common

- name: Удаление Apache2
  ansible.builtin.apt:
    pkg: apache2
    state: absent

- name: Обновление системы
  ansible.builtin.apt:
    pkg: "*"
    state: latest
    update_cache: yes
    
- name: Установка программ
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - "{{ packages_to_install }}"
#  when: ansible_distribution == "Ubuntu"
#  when: ansible_os_family == "Debian"

- name: Configuring zabbix-agent
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Restarting and enabling zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

#- include: tasks/ufw.yml
...
