---
- name: Ensure UFW is installed  
  ansible.builtin.apt:    
    pkg: ufw    
    state: present

- name: Outgoing allow
  community.general.ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: Allow OpenSSH rule
  community.general.ufw:
    rule: allow
    port: '22'    
    proto: tcp

- name: ufw rules
  community.general.ufw:
    rule: "allow"
    src: '192.168.10.0/24'
    port: "{{ item }}"
    proto: "tcp"
#  with_items:
#     - "80"
#     - "443"
  loop: '{{ allow_ports }}'

- name: Incoming deny
  community.general.ufw:
    state: enabled
    direction: incoming
    policy: deny
    logging: "on"
...
