---
# tasks file for nginx_proxy

- name: Установка Nginx
  apt:
    pkg: "nginx"
    state: present

- name: Подмена конфига балансировщика
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: "Nginx Reloader"

...